# All comments are written prepended by #
# Contact Kyle about editing this file. 

os:
  - linux

sudo: false

language: node_js
node_js:
  - "6.11.5"

cache:
  directories:
    - node_modules

before_install:

install:
  - npm install

before_script:

script:
  - npm run build
  - npm run lint
  - npm run test

after_success:
  - npm run coverage

after_failure:
